### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by raphaeltimbo** [ross-rotordynamics/ross-ml#1]
We should structure the project as a python package, so we need to have a `__init__.py` file so we can do something like:
```python
import rossml as rsml
```
More information about packages here https://docs.python.org/3/tutorial/modules.html#packages

**Comment by rodrigomoliveira1** [comment]
There was [commited](https://github.com/ross-rotordynamics/ross-ml/pull/4/commits/281aa4c3525f8d7f5958093900af2e7770876b3f) an `__init__.py` file. Although the syntax above is not being respected, there's another issue about chaning the folder's name. So, I believe we can close this issue.
